### ISSUE TITLE
How can I install it on a raspberry pi. Do you have some example please?

### ISSUE THREAD

**Issue by eduardjdejong** [the-maux/Chartboard#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by the-maux** [comment]
Hello @eduardjdejong,

You can use pip or docker.

> `git clone https://github.com/the-maux/Chartboard && cd Chartboard`
#### With Pip : 
```
virtualenv venv && source venv/bin/activate  
pip install -r requirements.txt  
python src/manage.py runserver 0.0.0.0:8080  
```
#### With Docker :
```
 docker build -t chartboard:0.1 .
 docker run chartboard:0.1
```

 Than, open your browser and go to http://0.0.0.0:8080

**Comment by eduardjdejong** [comment]
Hello,

I already have tipboard installed in tb-env. When I follow your
instructions I get an error

[image: image.png]

Is there something I have to do for migrating from tipboard to chartboard?

Kind regards

Eduard

Op ma 26 okt. 2020 om 10:56 schreef the-maux <notifications@github.com>:

**Comment by eduardjdejong** [comment]
Hi,

I got it working:

virtualenv venv && source venv/bin/activate
pip3 install -r requirements.txt
python3 src/manage.py runserver 0.0.0.0:8080

On a smart phone the url localhost:8080/chart shows on my smartphone. But I
cannot swip down to see other widget than te upper one

[image: image.png]

Is it a setting so I can see all widget on the smartphone. Now I cannot
swipe done....

Op ma 26 okt. 2020 om 10:56 schreef the-maux <notifications@github.com>:

**Comment by the-maux** [comment]
Hello @eduardjdejong ,

Chartboard is reponsive (thanks to flexbox),
So on a smartphone, you don't have to see charts, just scroll down 😃
