### ISSUE TITLE
Column based layout possible?

### ISSUE THREAD

**Issue by WEBudoGT** [the-maux/Chartboard#68]
**Is your feature request related to a problem? Please describe.**
I'm unable to use a column based layout in which there is a first column on the left, and there's a second column on the right divided into 3 rows.
I understand this was not possible with original tipboard, but maybe with this one it can be achieved?

**Describe the solution you'd like**
A way to declare col before row on the yaml.

**Additional context**
I understand tipbard didn't support it because of this one: https://github.com/allegro/tipboard/issues/49

**Comment by WEBudoGT** [comment]
I would like to achieve something similar to this: https://github.com/allegro/tipboard/files/121010/layput.txt
Based on this one: https://github.com/allegro/tipboard/issues/32
Sorry to include it as a comment, but I just found it after posting.

**Comment by the-maux** [comment]
Hello @WEBudoGT ,
Unfortunately no you cant
I did try to find a solution but didnt succeed 😞 
more info [here](https://github.com/the-maux/tipboard/wiki/Dashboard-Config-File#advanced-layout-with-weight-support)
